baseURL = 'https://grayfarer.github.io/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'nightfall'
publishDir = 'docs'
[params]
author = "GrayFarer"
user = "hello"
hostname = "grayfarer.github.io"
[[params.social]]
key = 1
name = "email"
url = "mailto:email@example.com"
